# File: message_models.py
from typing import List, Optional
from pydantic import BaseModel, Field
from .types import RoleLiteral
from .function_models import ToolCall, FunctionCall


class Message(BaseModel):
    role: RoleLiteral = Field(description="The role of the author of this message.")
    content: Optional[str] = Field(None, description="The contents of the message.")
    refusal: Optional[str] = Field(
        None, description="The refusal message generated by the model."
    )
    tool_calls: Optional[List[ToolCall]] = Field(
        None,
        description="The tool calls generated by the model, such as function calls.",
    )
    function_call: Optional[FunctionCall] = Field(
        None,
        description=(
            "Deprecated and replaced by tool_calls. The name and arguments "
            "of a function that should be called, as generated by the model."
        ),
    )
