# List of system fields to exclude from additional context processing
SYSTEM_FIELDS = [
    "ln_id",
    "id_",
    "node_id",
    "meta",
    "metadata",
    "timestamp",
    "created",
    "last_updated",
    "content",
    "page_content",
    "assignment",
    "assignments",
    "instruction",
    "context",
    "response_format",
    "sender",
    "recipient",
    "output_fields",
]
